#!/bin/sh
set -e

# Generate .env from Docker environment variables for the dotenv package
cat > /app/.env << EOF
PORT=${PORT:-4001}
USE_SSL=${USE_SSL:-false}
APP_NAME=${APP_NAME:-Nova Corp Verifier}
APP_VERSION=${APP_VERSION:-1.0.0}
VERIFIER_DID=${VERIFIER_DID}
VERIFIER_DOMAIN=${VERIFIER_DOMAIN}
SERVICE_DID=${SERVICE_DID}
MEDIATOR_DID=${MEDIATOR_DID}
MEDIATOR_URL=${MEDIATOR_URL}
ISSUER_MEDIATOR=${ISSUER_MEDIATOR:-${MEDIATOR_DID}}
STORAGE_BACKEND=${STORAGE_BACKEND:-json}
DATA_PATH=${DATA_PATH:-./data}
HK_TRUST_REGISTRY_URL=${HK_TRUST_REGISTRY_URL}
HK_TRUST_REGISTRY_DID=${HK_TRUST_REGISTRY_DID}
MACAU_TRUST_REGISTRY_URL=${MACAU_TRUST_REGISTRY_URL}
MACAU_TRUST_REGISTRY_DID=${MACAU_TRUST_REGISTRY_DID}
SG_TRUST_REGISTRY_URL=${SG_TRUST_REGISTRY_URL}
SG_TRUST_REGISTRY_DID=${SG_TRUST_REGISTRY_DID}
SG_EDUCATION_MINISTRY_DID=${SG_EDUCATION_MINISTRY_DID}
SG_EDUCATION_MINISTRY_TRUST_REGISTRY_URL=${SG_EDUCATION_MINISTRY_TRUST_REGISTRY_URL}
STUDENT_FIRST_NAME=${STUDENT_FIRST_NAME}
STUDENT_LAST_NAME=${STUDENT_LAST_NAME}
STUDENT_EMAIL=${STUDENT_EMAIL}
EOF

echo "✅ Generated .env file"
echo "🚀 Starting Verifier Backend on port ${PORT:-4001}..."

exec /app/bin/did_server
