# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and sign the application for distribution, upload to TestFlight"
    lane :beta do
      # Detect if we are running in CI, and create a temporary keychain
      # and switch match to readonly mode
      # https://docs.fastlane.tools/actions/setup_ci/
      setup_ci
      
      # Login to App Store Connect in order to perform actions later
      # in this process. Configuration provided by environment variables added
      # by the GitLab Apple Apps Store integration
      # https://docs.gitlab.com/ee/user/project/integrations/apple_app_store.html
      # https://docs.fastlane.tools/actions/app_store_connect_api_key/
      app_store_connect_api_key
      
      UI.important("Successfully connected to App Store Connect")

      # Download and install the correct signing certificates for the 
      # given build environment, in this case appstore
      # https://docs.fastlane.tools/actions/match/
      match(type: 'appstore', readonly: is_ci)

      # Get version number from the tag, fail if unset
      tag = ENV['CI_COMMIT_TAG']
      if tag.nil?
        UI.user_error!("CI_COMMIT_TAG environment variable is not set.")
      end

      # Set app version to release tag
      version_number = tag.gsub(/^v/, '').split('+')[0]
      increment_version_number(version_number: version_number)

      # Get latest build for the given version
      latest_build = latest_testflight_build_number(
        version: version_number,
        initial_build_number: 0
      )

      # Auto increment the build number for Test Flight
      # https://docs.fastlane.tools/actions/increment_build_number/
      # https://docs.fastlane.tools/actions/latest_testflight_build_number/
      build_number = increment_build_number(
        build_number: latest_build + 1,
        xcodeproj: "Runner.xcodeproj"
      )

      # Set the version number and build number in pubspec.yaml
      sh("sed -i '' 's/version:.*/version: #{version_number}+#{build_number}/' ../../pubspec.yaml")
      
      # Build app with flutter
      sh "flutter build ipa --dart-define-from-file=./configurations/.env --release --no-pub"

      # Build the app with the supplied configuration settings
      # Export method is the same as the match step above
      # Note: the difference between `appstore` and `app-store` is intentional
      # https://docs.fastlane.tools/actions/build_app/
      build_app(
        workspace: "Runner.xcworkspace",
        scheme: "Runner",
        configuration: "Release",
        export_method: "app-store",
        export_options: {
          provisioningProfiles: { 
            "com.experience.certizen" => "match AppStore com.experience.certizen",
          }
        },
        clean: true,
        skip_build_archive: true,
        export_team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
        archive_path: "../build/ios/archive/Runner.xcarchive"
      )

      UI.important(
        "Successfully prepared build #{version_number}+#{build_number} for upload to Testflight"
      )

      # Upload the newly created build to Test Flight using the App Store Connect
      # API key above, and the app configuration in the Appfile
      # https://docs.fastlane.tools/actions/upload_to_testflight/
      upload_to_testflight(
        skip_waiting_for_build_processing: true
      )
  end
end
